name: hostdeck
description: "Manage and monitor multiple AppHost accounts seamlessly with HostDeck"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  get: ^4.7.3
  dio: ^5.10.0
  flutter_secure_storage: ^10.3.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5
  intl: ^0.20.3
  url_launcher: ^6.3.2
  share_plus: ^13.2.0
  local_auth: ^3.0.1
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.6.0
  google_sign_in: ^7.2.0
  encrypt: ^5.0.3
  sign_in_button: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1
  package_rename_plus: ^1.11.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
